# Generated by Django 5.0.3 on 2024-03-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorName', models.CharField(max_length=100)),
                ('degree', models.CharField(default=False, max_length=500)),
                ('mobile', models.CharField(default=False, max_length=12)),
                ('weekday', models.CharField(default=False, max_length=500)),
                ('hospitalName', models.CharField(default=False, max_length=500)),
                ('address', models.CharField(default=False, max_length=500)),
                ('image', models.FileField(upload_to='images/')),
                ('age', models.IntegerField(null=True)),
                ('experience', models.IntegerField(default=False)),
                ('gender', models.CharField(max_length=500, null=True)),
                ('no_of_patient', models.IntegerField(null=True)),
                ('brief', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('specialist', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
