# Generated by Django 5.0.3 on 2024-03-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Upload', '0002_remove_doctor_details_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_details',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
